import ExcelJS from "exceljs";
import { AdvanceRegisterRow, AdvanceRegisterSummaryTotals, AdvanceRegisterFilterParams, TIMEZONE } from "./advance-register-query";
import { formatInTimeZone } from "date-fns-tz";
import prisma from "@/lib/db";

const ORG_NAME = "RADICAL HEALTH TECH PVT LTD";

function sanitizeForExcel(val: any): any {
  if (typeof val === "string") {
    if (/^[=+\-@\t\r]/.test(val)) {
      return `'${val}`;
    }
  }
  return val;
}

export async function generateAdvanceRegisterExcel(params: {
  rows: AdvanceRegisterRow[];
  summaryTotals: AdvanceRegisterSummaryTotals;
  filterParams: AdvanceRegisterFilterParams;
  generatedByUser: { name: string; email: string; role: string };
}): Promise<Uint8Array> {
  const { rows, summaryTotals, filterParams, generatedByUser } = params;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = `${generatedByUser.name} (${ORG_NAME})`;
  workbook.lastModifiedBy = generatedByUser.name;
  workbook.created = new Date();
  workbook.modified = new Date();

  // Color Palette
  const NAVY_DARK = "0F2744";
  const BLUE_HEADER = "1E3A5F";
  const BLUE_LIGHT = "F0F4F9";
  const GRAY_BORDER = "D9DFE7";
  const GREEN_ACCENT = "1B6A3C";
  const AMBER_ACCENT = "B45309";

  // -------------------------------------------------------------
  // SHEET 1: Advance Register Overview
  // -------------------------------------------------------------
  const ws1 = workbook.addWorksheet("Advance Register", {
    views: [{ showGridLines: true, state: "frozen", ySplit: 5 }],
  });

  // Title Header Banner
  ws1.mergeCells("A1:P1");
  const titleCell = ws1.getCell("A1");
  titleCell.value = `${ORG_NAME} — EMPLOYEE ADVANCE REGISTER`;
  titleCell.font = { name: "Arial", size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY_DARK } };
  titleCell.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
  ws1.getRow(1).height = 36;

  // Metadata Sub-banner
  ws1.mergeCells("A2:P2");
  const metaCell = ws1.getCell("A2");
  const timestamp = formatInTimeZone(new Date(), TIMEZONE, "dd-MMM-yyyy HH:mm:ss zzz");
  metaCell.value = `Generated: ${timestamp} | Generated By: ${generatedByUser.name} (${generatedByUser.email}) | Total Advances: ${rows.length}`;
  metaCell.font = { name: "Arial", size: 9, italic: true, color: { argb: "FFD0DCEB" } };
  metaCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "1A365D" } };
  metaCell.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
  ws1.getRow(2).height = 20;

  // KPI Summary Bar
  ws1.mergeCells("A3:P3");
  const kpiCell = ws1.getCell("A3");
  kpiCell.value = `TOTAL DISBURSED: ₹${summaryTotals.totalDisbursed.toLocaleString("en-IN", { minimumFractionDigits: 2 })}   |   EXPENSE ADJUSTED: ₹${summaryTotals.totalAdjusted.toLocaleString("en-IN", { minimumFractionDigits: 2 })}   |   EMPLOYEE RETURNED: ₹${summaryTotals.totalReturned.toLocaleString("en-IN", { minimumFractionDigits: 2 })}   |   OUTSTANDING BALANCE: ₹${summaryTotals.totalOutstanding.toLocaleString("en-IN", { minimumFractionDigits: 2 })}   |   AVAILABLE BALANCE: ₹${summaryTotals.totalAvailable.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
  kpiCell.font = { name: "Arial", size: 9.5, bold: true, color: { argb: "FF0F2744" } };
  kpiCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "E8EEF5" } };
  kpiCell.alignment = { vertical: "middle", horizontal: "left", indent: 1 };
  ws1.getRow(3).height = 24;

  // Empty Row
  ws1.getRow(4).height = 8;

  // Columns Header
  const headers = [
    "Advance #",
    "Employee Name",
    "Employee Email",
    "Role",
    "Purpose",
    "Status",
    "Requested (INR)",
    "Approved (INR)",
    "Disbursed (INR)",
    "Adjusted (INR)",
    "Returned (INR)",
    "Reserved (INR)",
    "Available (INR)",
    "Outstanding (INR)",
    "Payment Mode",
    "Payment Ref",
  ];

  const colWidths = [18, 22, 26, 14, 28, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 20];

  const headerRow = ws1.getRow(5);
  headers.forEach((h, idx) => {
    const cell = headerRow.getCell(idx + 1);
    cell.value = h;
    cell.font = { name: "Arial", size: 9, bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUE_HEADER } };
    cell.alignment = { vertical: "middle", horizontal: idx >= 6 && idx <= 13 ? "right" : "left", indent: 1 };
    ws1.getColumn(idx + 1).width = colWidths[idx];
  });
  headerRow.height = 24;

  // Populate Data Rows
  rows.forEach((r, idx) => {
    const row = ws1.getRow(6 + idx);
    row.values = [
      sanitizeForExcel(r.advanceNumber),
      sanitizeForExcel(r.requesterName),
      sanitizeForExcel(r.requesterEmail),
      sanitizeForExcel(r.requesterRole),
      sanitizeForExcel(r.purpose),
      sanitizeForExcel(r.status),
      r.requestedAmount,
      r.approvedAmount ?? "-",
      r.disbursedAmount,
      r.adjustedAmount,
      r.returnedAmount,
      r.reservedAmount,
      r.availableBalance,
      r.outstandingBalance,
      sanitizeForExcel(r.paymentMode || "-"),
      sanitizeForExcel(r.paymentReference || "-"),
    ];

    const isEven = idx % 2 === 1;
    for (let c = 1; c <= 16; c++) {
      const cell = row.getCell(c);
      cell.font = { name: "Arial", size: 8.5 };
      if (isEven) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "F9FAFC" } };
      }
      cell.border = {
        bottom: { style: "thin", color: { argb: GRAY_BORDER } },
        right: { style: "thin", color: { argb: GRAY_BORDER } },
      };
      if (c >= 7 && c <= 14) {
        if (typeof cell.value === "number") {
          cell.numFmt = "₹#,##0.00";
        }
        cell.alignment = { horizontal: "right" };
      } else {
        cell.alignment = { horizontal: "left", indent: 1 };
      }
    }
    row.height = 20;
  });

  // Add Summary Total Row
  const totalRowNum = 6 + rows.length;
  const totalRow = ws1.getRow(totalRowNum);
  totalRow.values = [
    "TOTAL",
    "",
    "",
    "",
    "",
    "",
    summaryTotals.totalRequested,
    summaryTotals.totalApproved,
    summaryTotals.totalDisbursed,
    summaryTotals.totalAdjusted,
    summaryTotals.totalReturned,
    summaryTotals.totalReserved,
    summaryTotals.totalAvailable,
    summaryTotals.totalOutstanding,
    "",
    "",
  ];
  totalRow.font = { name: "Arial", size: 9, bold: true, color: { argb: "FF0F2744" } };
  totalRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "E2E8F0" } };
  for (let c = 1; c <= 16; c++) {
    const cell = totalRow.getCell(c);
    cell.border = {
      top: { style: "medium", color: { argb: NAVY_DARK } },
      bottom: { style: "double", color: { argb: NAVY_DARK } },
    };
    if (c >= 7 && c <= 14) {
      if (typeof cell.value === "number") {
        cell.numFmt = "₹#,##0.00";
      }
      cell.alignment = { horizontal: "right" };
    }
  }
  totalRow.height = 24;

  const buffer = await workbook.xlsx.writeBuffer();
  return new Uint8Array(buffer as ArrayBuffer);
}
