import { PDFDocument, StandardFonts, rgb, degrees, PDFPage } from "pdf-lib";
import {
  CategoryAnalyticsResult,
  ORG_NAME,
  ORG_ADDRESS,
  TIMEZONE,
} from "./category-analytics-query";
import { formatInTimeZone } from "date-fns-tz";

function formatInr(val: number | null | undefined): string {
  if (val === null || val === undefined) return "0.00";
  return Number(val).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

/**
 * Generates a multi-page landscape PDF for Category Expense Analytics
 */
export async function generateCategoryAnalyticsPdf(params: {
  analytics: CategoryAnalyticsResult;
  generatedByUser: { name: string; email: string; role: string };
}): Promise<Uint8Array> {
  const { analytics, generatedByUser } = params;
  const { kpis, categories, subcategories, monthlyTrend, topVendors, activeFilters } = analytics;

  const pdfDoc = await PDFDocument.create();

  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const PAGE_WIDTH = 841.89; // Landscape A4
  const PAGE_HEIGHT = 595.28;
  const MARGIN_LEFT = 32;
  const MARGIN_RIGHT = 32;
  const MARGIN_TOP = 30;
  const MARGIN_BOTTOM = 30;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

  let currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursorY = PAGE_HEIGHT - MARGIN_TOP;

  const timestamp = formatInTimeZone(new Date(), TIMEZONE, "dd-MMM-yyyy HH:mm zzz");

  const checkNewPage = (neededHeight: number) => {
    if (cursorY - neededHeight < MARGIN_BOTTOM + 20) {
      drawFooter(currentPage);
      currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      cursorY = PAGE_HEIGHT - MARGIN_TOP;
      drawRunningHeader(currentPage);
    }
  };

  const drawRunningHeader = (page: PDFPage) => {
    page.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 18,
      width: CONTENT_WIDTH,
      height: 18,
      color: rgb(0.08, 0.2, 0.4),
    });

    page.drawText(`${ORG_NAME} - CATEGORY EXPENSE ANALYTICS`, {
      x: MARGIN_LEFT + 8,
      y: cursorY - 13,
      size: 8.5,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Address: ${ORG_ADDRESS} | Generated: ${timestamp}`, {
      x: PAGE_WIDTH - MARGIN_RIGHT - 260,
      y: cursorY - 13,
      size: 7.5,
      font: fontRegular,
      color: rgb(0.85, 0.9, 0.98),
    });

    cursorY -= 28;
  };

  const drawFooter = (page: PDFPage) => {
    page.drawLine({
      start: { x: MARGIN_LEFT, y: MARGIN_BOTTOM },
      end: { x: PAGE_WIDTH - MARGIN_RIGHT, y: MARGIN_BOTTOM },
      thickness: 0.5,
      color: rgb(0.7, 0.75, 0.8),
    });

    page.drawText("CONFIDENTIAL - INTERNAL EXECUTIVE ANALYTICS REPORT", {
      x: MARGIN_LEFT,
      y: MARGIN_BOTTOM - 12,
      size: 7,
      font: fontBold,
      color: rgb(0.5, 0.55, 0.6),
    });
  };

  // ==========================================
  // PAGE 1: PRIMARY HEADER & KPI DASHBOARD
  // ==========================================
  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 38,
    width: CONTENT_WIDTH,
    height: 38,
    color: rgb(0.08, 0.2, 0.4),
  });

  currentPage.drawText(ORG_NAME, {
    x: MARGIN_LEFT + 10,
    y: cursorY - 16,
    size: 13,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  currentPage.drawText(`Corporate Office: ${ORG_ADDRESS}`, {
    x: MARGIN_LEFT + 10,
    y: cursorY - 30,
    size: 7.5,
    font: fontRegular,
    color: rgb(0.85, 0.9, 0.98),
  });

  currentPage.drawText("CATEGORY EXPENSE ANALYTICS REPORT", {
    x: PAGE_WIDTH - MARGIN_RIGHT - 240,
    y: cursorY - 16,
    size: 11,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  currentPage.drawText(`Generated by: ${generatedByUser.name} (${generatedByUser.role})`, {
    x: PAGE_WIDTH - MARGIN_RIGHT - 240,
    y: cursorY - 30,
    size: 7.5,
    font: fontRegular,
    color: rgb(0.85, 0.9, 0.98),
  });

  cursorY -= 46;

  // Filter Summary Line
  const filterDescParts: string[] = [];
  if (activeFilters.filterMode === "DATE_RANGE") {
    filterDescParts.push(`Date Range (${activeFilters.dateBasis || "EXPENSE_DATE"}): ${activeFilters.fromDate || "All"} to ${activeFilters.toDate || "All"}`);
  } else if (activeFilters.filterMode === "MULTIPLE_MONTHS") {
    filterDescParts.push(`Months: ${activeFilters.selectedMonths?.join(", ") || "All"} (Year ${activeFilters.year || new Date().getFullYear()})`);
  }
  filterDescParts.push(`Statuses: ${activeFilters.statuses?.join(", ") || "APPROVED, REIMBURSED"}`);
  if (activeFilters.vendorName) filterDescParts.push(`Vendor: ${activeFilters.vendorName}`);

  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 20,
    width: CONTENT_WIDTH,
    height: 20,
    borderColor: rgb(0.8, 0.85, 0.9),
    borderWidth: 0.5,
    color: rgb(0.96, 0.97, 1),
  });

  currentPage.drawText(`Applied Filters: ${filterDescParts.join(" | ")}`, {
    x: MARGIN_LEFT + 8,
    y: cursorY - 14,
    size: 7.5,
    font: fontRegular,
    color: rgb(0.2, 0.25, 0.35),
  });

  cursorY -= 28;

  // 8 KPI Summary Cards (2 rows of 4 cards)
  const cardW = (CONTENT_WIDTH - 30) / 4;
  const cardH = 38;

  const kpiRow1 = [
    { label: "TOTAL EXPENSE", val: `INR ${formatInr(kpis.totalExpense)}`, color: rgb(0.08, 0.45, 0.2) },
    { label: "TOTAL REIMBURSED", val: `INR ${formatInr(kpis.totalReimbursed)}`, color: rgb(0.1, 0.35, 0.7) },
    { label: "AWAITING DISBURSEMENT", val: `INR ${formatInr(kpis.approvedAwaitingReimbursement)}`, color: rgb(0.7, 0.4, 0.1) },
    { label: "TOTAL GST TAX", val: `INR ${formatInr(kpis.totalGst)}`, color: rgb(0.15, 0.2, 0.3) },
  ];

  const kpiRow2 = [
    { label: "EXPENSE ITEMS", val: `${kpis.itemCount} Items`, color: rgb(0.08, 0.2, 0.4) },
    { label: "AVG ITEM SPEND", val: `INR ${formatInr(kpis.averageExpenseAmount)}`, color: rgb(0.2, 0.25, 0.35) },
    { label: "TOP CATEGORY", val: kpis.highestExpenseCategory ? `${kpis.highestExpenseCategory.name.substring(0, 15)}` : "-", color: rgb(0.5, 0.15, 0.6) },
    { label: "TOP VENDOR", val: kpis.highestExpenseVendor ? `${kpis.highestExpenseVendor.name.substring(0, 15)}` : "-", color: rgb(0.08, 0.3, 0.5) },
  ];

  const renderCardRow = (cards: typeof kpiRow1) => {
    cards.forEach((card, idx) => {
      const posX = MARGIN_LEFT + idx * (cardW + 10);
      currentPage.drawRectangle({
        x: posX,
        y: cursorY - cardH,
        width: cardW,
        height: cardH,
        borderColor: rgb(0.82, 0.86, 0.92),
        borderWidth: 1,
        color: rgb(0.98, 0.99, 1),
      });

      currentPage.drawText(card.label, {
        x: posX + 8,
        y: cursorY - 14,
        size: 7,
        font: fontBold,
        color: rgb(0.4, 0.45, 0.5),
      });

      currentPage.drawText(card.val, {
        x: posX + 8,
        y: cursorY - 30,
        size: 9.5,
        font: fontBold,
        color: card.color,
      });
    });
    cursorY -= cardH + 8;
  };

  renderCardRow(kpiRow1);
  renderCardRow(kpiRow2);

  cursorY -= 8;

  // ==========================================
  // SECTION: TOP CATEGORIES & VISUAL SHARE
  // ==========================================
  currentPage.drawText("CATEGORY BREAKDOWN & SHARE SUMMARY", {
    x: MARGIN_LEFT,
    y: cursorY,
    size: 10,
    font: fontBold,
    color: rgb(0.08, 0.2, 0.4),
  });
  cursorY -= 14;

  // Category Table Header
  const catColWidths = [120, 180, 70, 90, 85, 95, 80, 58];
  const catHeaders = ["Code", "Category Name", "Items", "Taxable (INR)", "GST (INR)", "Total Spend (INR)", "Avg (INR)", "Share"];

  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 16,
    width: CONTENT_WIDTH,
    height: 16,
    color: rgb(0.08, 0.2, 0.4),
  });

  let curX = MARGIN_LEFT;
  catHeaders.forEach((h, idx) => {
    currentPage.drawText(h, {
      x: curX + 4,
      y: cursorY - 11,
      size: 7.5,
      font: fontBold,
      color: rgb(1, 1, 1),
    });
    curX += catColWidths[idx];
  });
  cursorY -= 18;

  // Category Table Rows
  categories.forEach((cat, idx) => {
    checkNewPage(16);
    const isEven = idx % 2 === 0;

    currentPage.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 15,
      width: CONTENT_WIDTH,
      height: 15,
      borderColor: rgb(0.88, 0.9, 0.94),
      borderWidth: 0.5,
      color: isEven ? rgb(0.98, 0.99, 1) : rgb(1, 1, 1),
    });

    const rowVals = [
      cat.categoryCode,
      cat.categoryName.substring(0, 28),
      String(cat.itemCount),
      formatInr(cat.taxableValue),
      formatInr(cat.totalGst),
      formatInr(cat.totalAmount),
      formatInr(cat.avgAmount),
      `${cat.percentageOfTotal}%`,
    ];

    let rowX = MARGIN_LEFT;
    rowVals.forEach((val, cIdx) => {
      currentPage.drawText(val, {
        x: rowX + 4,
        y: cursorY - 10.5,
        size: 7,
        font: cIdx === 5 ? fontBold : fontRegular,
        color: rgb(0.1, 0.15, 0.2),
      });
      rowX += catColWidths[cIdx];
    });

    cursorY -= 15;
  });

  cursorY -= 16;

  // ==========================================
  // SECTION: TOP VENDORS SUMMARY
  // ==========================================
  checkNewPage(100);
  currentPage.drawText("TOP VENDORS & MERCHANTS SUMMARY", {
    x: MARGIN_LEFT,
    y: cursorY,
    size: 10,
    font: fontBold,
    color: rgb(0.08, 0.2, 0.4),
  });
  cursorY -= 14;

  const vendorColWidths = [240, 90, 130, 110, 130, 78];
  const vendorHeaders = ["Vendor Name", "Item Count", "Taxable Value (INR)", "GST (INR)", "Total Spend (INR)", "Share"];

  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 16,
    width: CONTENT_WIDTH,
    height: 16,
    color: rgb(0.08, 0.2, 0.4),
  });

  curX = MARGIN_LEFT;
  vendorHeaders.forEach((h, idx) => {
    currentPage.drawText(h, {
      x: curX + 4,
      y: cursorY - 11,
      size: 7.5,
      font: fontBold,
      color: rgb(1, 1, 1),
    });
    curX += vendorColWidths[idx];
  });
  cursorY -= 18;

  topVendors.slice(0, 10).forEach((v, idx) => {
    checkNewPage(15);
    const isEven = idx % 2 === 0;

    currentPage.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 15,
      width: CONTENT_WIDTH,
      height: 15,
      borderColor: rgb(0.88, 0.9, 0.94),
      borderWidth: 0.5,
      color: isEven ? rgb(0.98, 0.99, 1) : rgb(1, 1, 1),
    });

    const vVals = [
      v.vendorName.substring(0, 36),
      String(v.itemCount),
      formatInr(v.taxableValue),
      formatInr(v.totalGst),
      formatInr(v.totalAmount),
      `${v.percentageOfTotal}%`,
    ];

    let rowX = MARGIN_LEFT;
    vVals.forEach((val, cIdx) => {
      currentPage.drawText(val, {
        x: rowX + 4,
        y: cursorY - 10.5,
        size: 7,
        font: cIdx === 4 ? fontBold : fontRegular,
        color: rgb(0.1, 0.15, 0.2),
      });
      rowX += vendorColWidths[cIdx];
    });

    cursorY -= 15;
  });

  drawFooter(currentPage);

  // Add Page Numbers
  const totalPages = pdfDoc.getPageCount();
  const pages = pdfDoc.getPages();
  for (let i = 0; i < totalPages; i++) {
    const page = pages[i];
    const pageNumStr = `Page ${i + 1} of ${totalPages}`;
    page.drawText(pageNumStr, {
      x: PAGE_WIDTH - MARGIN_RIGHT - fontRegular.widthOfTextAtSize(pageNumStr, 7),
      y: MARGIN_BOTTOM - 12,
      size: 7,
      font: fontRegular,
      color: rgb(0.5, 0.55, 0.6),
    });
  }

  return await pdfDoc.save();
}
