import ExcelJS from "exceljs";
import {
  CategoryAnalyticsResult,
  ORG_NAME,
  ORG_ADDRESS,
  TIMEZONE,
} from "./category-analytics-query";
import { formatInTimeZone } from "date-fns-tz";

function sanitizeForExcel(val: any): any {
  if (typeof val === "string" && /^[=+\-@\t\r]/.test(val)) {
    return `'${val}`;
  }
  return val;
}

/**
 * Builds a multi-sheet styled Excel workbook for Category Expense Analytics
 */
export async function generateCategoryAnalyticsExcel(params: {
  analytics: CategoryAnalyticsResult;
  generatedByUser: { name: string; email: string; role: string };
}): Promise<Buffer> {
  const { analytics, generatedByUser } = params;
  const { kpis, categories, subcategories, monthlyTrend, topVendors, activeFilters } = analytics;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = `${ORG_NAME} - Analytics Engine`;
  workbook.created = new Date();

  const timestamp = formatInTimeZone(new Date(), TIMEZONE, "dd-MMM-yyyy HH:mm:ss zzz");

  // Helper for consistent header styling
  const styleHeaderRow = (row: ExcelJS.Row, bgHex = "FF1E3A8A") => {
    row.height = 24;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: bgHex } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFCCCCCC" } },
        bottom: { style: "medium", color: { argb: "FF0F2B5C" } },
        left: { style: "thin", color: { argb: "FFCCCCCC" } },
        right: { style: "thin", color: { argb: "FFCCCCCC" } },
      };
    });
  };

  // ==========================================
  // SHEET 1: CATEGORY SUMMARY
  // ==========================================
  const wsCat = workbook.addWorksheet("Category Summary", {
    views: [{ state: "frozen", ySplit: 5 }],
  });

  // Title Block
  wsCat.mergeCells("A1:I1");
  wsCat.getCell("A1").value = `${ORG_NAME} - CATEGORY EXPENSE SUMMARY`;
  wsCat.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsCat.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };
  wsCat.getRow(1).height = 26;

  wsCat.mergeCells("A2:I2");
  wsCat.getCell("A2").value = `Generated By: ${generatedByUser.name} (${generatedByUser.role}) | ${timestamp} | Address: ${ORG_ADDRESS}`;
  wsCat.getCell("A2").font = { name: "Calibri", size: 9, italic: true, color: { argb: "FF555555" } };
  wsCat.getCell("A2").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF7F9FC" } };
  wsCat.getRow(2).height = 18;

  wsCat.getRow(3).height = 8; // Spacer

  // Header Row (Row 4)
  const catHeaders = [
    "Category Code",
    "Category Name",
    "Item Count",
    "Taxable Value (INR)",
    "Total GST (INR)",
    "Total Expense (INR)",
    "Average Amount (INR)",
    "Highest Expense (INR)",
    "% Share of Total",
  ];
  wsCat.getRow(4).values = catHeaders;
  styleHeaderRow(wsCat.getRow(4), "FF1E3A8A");

  // Data Rows
  let catRowNum = 5;
  for (const c of categories) {
    const row = wsCat.getRow(catRowNum);
    row.values = [
      c.categoryCode,
      c.categoryName,
      c.itemCount,
      c.taxableValue,
      c.totalGst,
      c.totalAmount,
      c.avgAmount,
      c.maxAmount,
      `${c.percentageOfTotal}%`,
    ];

    row.getCell(1).alignment = { horizontal: "center" };
    row.getCell(3).alignment = { horizontal: "center" };
    row.getCell(4).numFmt = "₹#,##0.00";
    row.getCell(5).numFmt = "₹#,##0.00";
    row.getCell(6).numFmt = "₹#,##0.00";
    row.getCell(7).numFmt = "₹#,##0.00";
    row.getCell(8).numFmt = "₹#,##0.00";
    row.getCell(9).alignment = { horizontal: "right" };

    const isEven = catRowNum % 2 === 0;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 9.5 };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: isEven ? "FFF9FAFB" : "FFFFFFFF" } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
        left: { style: "thin", color: { argb: "FFE5E7EB" } },
        right: { style: "thin", color: { argb: "FFE5E7EB" } },
      };
    });
    catRowNum++;
  }

  // Totals Row
  const catTotalsRow = wsCat.getRow(catRowNum);
  catTotalsRow.values = [
    "TOTAL",
    "ALL CATEGORIES",
    kpis.itemCount,
    kpis.totalTaxableValue,
    kpis.totalGst,
    kpis.totalExpense,
    kpis.averageExpenseAmount,
    "-",
    "100.00%",
  ];
  catTotalsRow.height = 22;
  catTotalsRow.eachCell((cell) => {
    cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF0F2B5C" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE0E7FF" } };
    cell.border = {
      top: { style: "medium", color: { argb: "FF1E3A8A" } },
      bottom: { style: "double", color: { argb: "FF1E3A8A" } },
      left: { style: "thin", color: { argb: "FFCCCCCC" } },
      right: { style: "thin", color: { argb: "FFCCCCCC" } },
    };
  });
  catTotalsRow.getCell(4).numFmt = "₹#,##0.00";
  catTotalsRow.getCell(5).numFmt = "₹#,##0.00";
  catTotalsRow.getCell(6).numFmt = "₹#,##0.00";
  catTotalsRow.getCell(7).numFmt = "₹#,##0.00";

  wsCat.columns = [
    { width: 16 },
    { width: 28 },
    { width: 14 },
    { width: 20 },
    { width: 18 },
    { width: 22 },
    { width: 20 },
    { width: 20 },
    { width: 16 },
  ];
  wsCat.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: 9 } };

  // ==========================================
  // SHEET 2: SUBCATEGORY SUMMARY
  // ==========================================
  const wsSub = workbook.addWorksheet("Subcategory Summary", {
    views: [{ state: "frozen", ySplit: 5 }],
  });

  wsSub.mergeCells("A1:K1");
  wsSub.getCell("A1").value = `${ORG_NAME} - SUBCATEGORY EXPENSE BREAKDOWN`;
  wsSub.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsSub.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };
  wsSub.getRow(1).height = 26;

  wsSub.mergeCells("A2:K2");
  wsSub.getCell("A2").value = `Generated By: ${generatedByUser.name} | ${timestamp}`;
  wsSub.getCell("A2").font = { name: "Calibri", size: 9, italic: true, color: { argb: "FF555555" } };
  wsSub.getCell("A2").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF7F9FC" } };

  const subHeaders = [
    "Category Name",
    "Subcategory Code",
    "Subcategory Name",
    "Item Count",
    "Taxable Value (INR)",
    "Total GST (INR)",
    "Total Expense (INR)",
    "Average Amount (INR)",
    "Highest Expense (INR)",
    "% of Category",
    "% of Total Spend",
  ];
  wsSub.getRow(4).values = subHeaders;
  styleHeaderRow(wsSub.getRow(4), "FF1E3A8A");

  let subRowNum = 5;
  for (const s of subcategories) {
    const row = wsSub.getRow(subRowNum);
    row.values = [
      s.categoryName,
      s.subcategoryCode,
      s.subcategoryName,
      s.itemCount,
      s.taxableValue,
      s.totalGst,
      s.totalAmount,
      s.avgAmount,
      s.maxAmount,
      `${s.percentageOfCategory}%`,
      `${s.percentageOfTotal}%`,
    ];

    row.getCell(4).alignment = { horizontal: "center" };
    row.getCell(5).numFmt = "₹#,##0.00";
    row.getCell(6).numFmt = "₹#,##0.00";
    row.getCell(7).numFmt = "₹#,##0.00";
    row.getCell(8).numFmt = "₹#,##0.00";
    row.getCell(9).numFmt = "₹#,##0.00";
    row.getCell(10).alignment = { horizontal: "right" };
    row.getCell(11).alignment = { horizontal: "right" };

    const isEven = subRowNum % 2 === 0;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 9.5 };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: isEven ? "FFF9FAFB" : "FFFFFFFF" } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
        left: { style: "thin", color: { argb: "FFE5E7EB" } },
        right: { style: "thin", color: { argb: "FFE5E7EB" } },
      };
    });
    subRowNum++;
  }

  wsSub.columns = [
    { width: 24 },
    { width: 16 },
    { width: 26 },
    { width: 14 },
    { width: 20 },
    { width: 18 },
    { width: 20 },
    { width: 20 },
    { width: 20 },
    { width: 16 },
    { width: 16 },
  ];
  wsSub.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: 11 } };

  // ==========================================
  // SHEET 3: MONTHLY TREND
  // ==========================================
  const wsTrend = workbook.addWorksheet("Monthly Trend", {
    views: [{ state: "frozen", ySplit: 5 }],
  });

  const catNames = categories.map((c) => c.categoryName);
  const trendHeaders = ["Month", "Total Monthly Spend (INR)", ...catNames];

  wsTrend.mergeCells(1, 1, 1, trendHeaders.length);
  wsTrend.getCell(1, 1).value = `${ORG_NAME} - MONTHLY EXPENSE TREND BY CATEGORY`;
  wsTrend.getCell(1, 1).font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsTrend.getCell(1, 1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  wsTrend.getRow(4).values = trendHeaders;
  styleHeaderRow(wsTrend.getRow(4), "FF1E3A8A");

  let trendRowNum = 5;
  for (const m of monthlyTrend) {
    const rowVals: any[] = [m.monthLabel, m.totalAmount];
    for (const catName of catNames) {
      rowVals.push(m.categoryBreakdown[catName] || 0);
    }

    const row = wsTrend.getRow(trendRowNum);
    row.values = rowVals;

    row.getCell(2).numFmt = "₹#,##0.00";
    for (let cIdx = 3; cIdx <= trendHeaders.length; cIdx++) {
      row.getCell(cIdx).numFmt = "₹#,##0.00";
    }

    const isEven = trendRowNum % 2 === 0;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 9.5 };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: isEven ? "FFF9FAFB" : "FFFFFFFF" } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
        left: { style: "thin", color: { argb: "FFE5E7EB" } },
        right: { style: "thin", color: { argb: "FFE5E7EB" } },
      };
    });
    trendRowNum++;
  }

  wsTrend.columns = [
    { width: 16 },
    { width: 24 },
    ...catNames.map(() => ({ width: 22 })),
  ];
  wsTrend.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: trendHeaders.length } };

  // ==========================================
  // SHEET 4: TOP VENDORS
  // ==========================================
  const wsVendors = workbook.addWorksheet("Top Vendors", {
    views: [{ state: "frozen", ySplit: 5 }],
  });

  wsVendors.mergeCells("A1:F1");
  wsVendors.getCell("A1").value = `${ORG_NAME} - TOP VENDORS / MERCHANTS`;
  wsVendors.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsVendors.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  const vendorHeaders = [
    "Vendor / Merchant",
    "Item Count",
    "Taxable Value (INR)",
    "Total GST (INR)",
    "Total Expense (INR)",
    "% Share of Total",
  ];
  wsVendors.getRow(4).values = vendorHeaders;
  styleHeaderRow(wsVendors.getRow(4), "FF1E3A8A");

  let vRowNum = 5;
  for (const v of topVendors) {
    const row = wsVendors.getRow(vRowNum);
    row.values = [
      v.vendorName,
      v.itemCount,
      v.taxableValue,
      v.totalGst,
      v.totalAmount,
      `${v.percentageOfTotal}%`,
    ];

    row.getCell(2).alignment = { horizontal: "center" };
    row.getCell(3).numFmt = "₹#,##0.00";
    row.getCell(4).numFmt = "₹#,##0.00";
    row.getCell(5).numFmt = "₹#,##0.00";
    row.getCell(6).alignment = { horizontal: "right" };

    const isEven = vRowNum % 2 === 0;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 9.5 };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: isEven ? "FFF9FAFB" : "FFFFFFFF" } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
        left: { style: "thin", color: { argb: "FFE5E7EB" } },
        right: { style: "thin", color: { argb: "FFE5E7EB" } },
      };
    });
    vRowNum++;
  }

  wsVendors.columns = [
    { width: 30 },
    { width: 14 },
    { width: 20 },
    { width: 18 },
    { width: 22 },
    { width: 16 },
  ];
  wsVendors.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: 6 } };

  // ==========================================
  // SHEET 5: APPLIED FILTERS & KPIS
  // ==========================================
  const wsKpis = workbook.addWorksheet("Applied Filters & KPIs");

  wsKpis.mergeCells("A1:D1");
  wsKpis.getCell("A1").value = `${ORG_NAME} - EXECUTIVE KPI SUMMARY`;
  wsKpis.getCell("A1").font = { name: "Calibri", size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  wsKpis.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  wsKpis.getCell("A3").value = "METRIC";
  wsKpis.getCell("B3").value = "CURRENT PERIOD VALUE";
  wsKpis.getCell("C3").value = "PREVIOUS PERIOD";
  wsKpis.getCell("D3").value = "VARIANCE / DELTA %";
  styleHeaderRow(wsKpis.getRow(3), "FF1E3A8A");

  const kpiRows = [
    ["Total Expense Amount", kpis.totalExpense, kpis.previousPeriod?.totalExpense ?? "-", kpis.previousPeriod?.expenseDeltaPct !== undefined ? `${kpis.previousPeriod.expenseDeltaPct}%` : "-"],
    ["Total Reimbursed Amount", kpis.totalReimbursed, kpis.previousPeriod?.totalReimbursed ?? "-", kpis.previousPeriod?.reimbursedDeltaPct !== undefined ? `${kpis.previousPeriod.reimbursedDeltaPct}%` : "-"],
    ["Approved Awaiting Reimbursement", kpis.approvedAwaitingReimbursement, "-", "-"],
    ["Total GST Taxes", kpis.totalGst, kpis.previousPeriod?.totalGst ?? "-", "-"],
    ["Taxable Value", kpis.totalTaxableValue, "-", "-"],
    ["Total Expense Items Count", kpis.itemCount, kpis.previousPeriod?.itemCount ?? "-", "-"],
    ["Average Expense per Item", kpis.averageExpenseAmount, kpis.previousPeriod?.averageExpenseAmount ?? "-", "-"],
    ["Highest Expense Category", kpis.highestExpenseCategory ? `${kpis.highestExpenseCategory.name} (₹${kpis.highestExpenseCategory.amount.toLocaleString("en-IN")})` : "-", "-", "-"],
    ["Highest Expense Vendor", kpis.highestExpenseVendor ? `${kpis.highestExpenseVendor.name} (₹${kpis.highestExpenseVendor.amount.toLocaleString("en-IN")})` : "-", "-", "-"],
  ];

  let kpiRowNum = 4;
  for (const r of kpiRows) {
    const row = wsKpis.getRow(kpiRowNum);
    row.values = r;
    if (typeof r[1] === "number" && kpiRowNum <= 10) {
      row.getCell(2).numFmt = "₹#,##0.00";
    }
    kpiRowNum++;
  }

  // Filter Details block
  wsKpis.getCell("A16").value = "APPLIED FILTER SETTINGS";
  wsKpis.getCell("A16").font = { name: "Calibri", size: 11, bold: true, color: { argb: "FF0F2B5C" } };

  wsKpis.getCell("A17").value = "Filter Mode";
  wsKpis.getCell("B17").value = activeFilters.filterMode || "DATE_RANGE";
  wsKpis.getCell("A18").value = "Date Basis";
  wsKpis.getCell("B18").value = activeFilters.dateBasis || "EXPENSE_DATE";
  wsKpis.getCell("A19").value = "Date Range";
  wsKpis.getCell("B19").value = `${activeFilters.fromDate || "All"} to ${activeFilters.toDate || "All"}`;
  wsKpis.getCell("A20").value = "Statuses";
  wsKpis.getCell("B20").value = activeFilters.statuses?.join(", ") || "APPROVED, REIMBURSED (Default)";
  wsKpis.getCell("A21").value = "Company Address";
  wsKpis.getCell("B21").value = ORG_ADDRESS;

  wsKpis.columns = [{ width: 32 }, { width: 28 }, { width: 22 }, { width: 20 }];

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
