import ExcelJS from "exceljs";
import {
  GstAnalyticsData,
  GstRegisterRow,
  GstRegisterFilterParams,
  ORG_NAME,
  ORG_ADDRESS,
  GST_DISCLAIMER,
  TIMEZONE,
} from "./gst-register-query";
import { formatInTimeZone } from "date-fns-tz";

function sanitizeForExcel(val: any): any {
  if (typeof val === "string" && /^[=+\-@\t\r]/.test(val)) {
    return `'${val}`;
  }
  return val;
}

/**
 * Generates an 8-sheet styled Excel workbook for the GST Expense Register
 */
export async function generateGstRegisterExcel(params: {
  rows: GstRegisterRow[];
  analytics: GstAnalyticsData;
  filterParams: GstRegisterFilterParams;
  generatedByUser: { name: string; email: string; role: string };
}): Promise<Buffer> {
  const { rows, analytics, filterParams, generatedByUser } = params;
  const { kpis, monthlyTrend, taxComponents, ratesBreakdown, itcBreakdown, categoriesSummary, vendorsSummary, rcmTransactions, exceptionsList } = analytics;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = `${ORG_NAME} - GST Register Engine`;
  workbook.created = new Date();

  const timestamp = formatInTimeZone(new Date(), TIMEZONE, "dd-MMM-yyyy HH:mm:ss zzz");

  const styleHeaderRow = (row: ExcelJS.Row, bgHex = "FF1E3A8A") => {
    row.height = 24;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: bgHex } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFCCCCCC" } },
        bottom: { style: "medium", color: { argb: "FF0F2B5C" } },
        left: { style: "thin", color: { argb: "FFCCCCCC" } },
        right: { style: "thin", color: { argb: "FFCCCCCC" } },
      };
    });
  };

  // ==========================================
  // SHEET 1: GST TRANSACTIONS
  // ==========================================
  const wsTx = workbook.addWorksheet("GST Transactions", {
    views: [{ state: "frozen", ySplit: 5 }],
  });

  wsTx.mergeCells("A1:AE1");
  wsTx.getCell("A1").value = `${ORG_NAME} - GST EXPENSE REGISTER (ITEMIZED TRANSACTIONS)`;
  wsTx.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsTx.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };
  wsTx.getRow(1).height = 26;

  wsTx.mergeCells("A2:AE2");
  wsTx.getCell("A2").value = `${GST_DISCLAIMER} | Generated By: ${generatedByUser.name} (${generatedByUser.role}) | ${timestamp} | Address: ${ORG_ADDRESS}`;
  wsTx.getCell("A2").font = { name: "Calibri", size: 9, italic: true, color: { argb: "FF555555" } };
  wsTx.getCell("A2").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF7F9FC" } };
  wsTx.getRow(2).height = 18;

  const txHeaders = [
    "Report #",
    "Expense Tag",
    "Status",
    "Expense Date",
    "Invoice Date",
    "Invoice #",
    "Vendor / Merchant",
    "Vendor GST Reg",
    "Vendor GSTIN",
    "Doc Type",
    "GST Treatment",
    "Category",
    "Place of Supply",
    "HSN/SAC",
    "Tax Mode",
    "Taxable Value (INR)",
    "GST Rate",
    "CGST Rate",
    "CGST (INR)",
    "SGST Rate",
    "SGST (INR)",
    "IGST Rate",
    "IGST (INR)",
    "Cess (INR)",
    "Total GST (INR)",
    "Gross Total (INR)",
    "Reverse Charge",
    "ITC Eligibility",
    "Submitted By",
    "Receipts",
    "Exceptions",
  ];

  wsTx.getRow(4).values = txHeaders;
  styleHeaderRow(wsTx.getRow(4), "FF1E3A8A");

  let rNum = 5;
  for (const r of rows) {
    const row = wsTx.getRow(rNum);
    row.values = [
      r.reportNumber,
      r.tagTitle,
      r.status,
      r.expenseDate,
      r.invoiceDate || "-",
      r.invoiceNumber || "-",
      r.vendorName,
      r.vendorGstStatus || "-",
      r.vendorGstin || "-",
      r.documentType || "-",
      r.gstTreatmentName,
      r.categoryName,
      r.placeOfSupply || "-",
      r.hsnSacCode || "-",
      r.taxMode || "-",
      r.taxableValue,
      r.gstRateLabel,
      r.cgstRate ? `${r.cgstRate}%` : "-",
      r.cgstAmount,
      r.sgstRate ? `${r.sgstRate}%` : "-",
      r.sgstAmount,
      r.igstRate ? `${r.igstRate}%` : "-",
      r.igstAmount,
      r.cessAmount,
      r.totalGstAmount,
      r.grossAmount,
      r.reverseCharge ? "YES" : "NO",
      r.itcEligibility,
      r.submittedBy,
      r.evidenceCount,
      r.exceptionCount > 0 ? `${r.exceptionCount} Issue(s)` : "None",
    ];

    row.getCell(16).numFmt = "₹#,##0.00";
    row.getCell(19).numFmt = "₹#,##0.00";
    row.getCell(21).numFmt = "₹#,##0.00";
    row.getCell(23).numFmt = "₹#,##0.00";
    row.getCell(24).numFmt = "₹#,##0.00";
    row.getCell(25).numFmt = "₹#,##0.00";
    row.getCell(26).numFmt = "₹#,##0.00";

    const isEven = rNum % 2 === 0;
    row.eachCell((cell) => {
      cell.font = { name: "Calibri", size: 9.5 };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: isEven ? "FFF9FAFB" : "FFFFFFFF" } };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
        left: { style: "thin", color: { argb: "FFE5E7EB" } },
        right: { style: "thin", color: { argb: "FFE5E7EB" } },
      };
    });
    rNum++;
  }

  // Totals Row
  const txTotals = wsTx.getRow(rNum);
  txTotals.values = [
    "TOTALS",
    `${rows.length} Items`,
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    kpis.taxableValue,
    "",
    "",
    kpis.cgst,
    "",
    kpis.sgst,
    "",
    kpis.igst,
    kpis.cess,
    kpis.totalGst,
    kpis.grossExpense,
    "",
    "",
    "",
    "",
    `${kpis.exceptionCount} Total Flags`,
  ];
  txTotals.height = 22;
  txTotals.eachCell((cell) => {
    cell.font = { name: "Calibri", size: 10, bold: true, color: { argb: "FF0F2B5C" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE0E7FF" } };
    cell.border = {
      top: { style: "medium", color: { argb: "FF1E3A8A" } },
      bottom: { style: "double", color: { argb: "FF1E3A8A" } },
    };
  });
  txTotals.getCell(16).numFmt = "₹#,##0.00";
  txTotals.getCell(19).numFmt = "₹#,##0.00";
  txTotals.getCell(21).numFmt = "₹#,##0.00";
  txTotals.getCell(23).numFmt = "₹#,##0.00";
  txTotals.getCell(24).numFmt = "₹#,##0.00";
  txTotals.getCell(25).numFmt = "₹#,##0.00";
  txTotals.getCell(26).numFmt = "₹#,##0.00";

  wsTx.columns = txHeaders.map(() => ({ width: 18 }));
  wsTx.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: txHeaders.length } };

  // ==========================================
  // SHEET 2: GST SUMMARY (MONTHLY & COMPONENTS)
  // ==========================================
  const wsSum = workbook.addWorksheet("GST Summary");
  wsSum.mergeCells("A1:H1");
  wsSum.getCell("A1").value = `${ORG_NAME} - MONTHLY GST TAX SUMMARY`;
  wsSum.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsSum.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  const sumHeaders = ["Month", "Taxable Value (INR)", "CGST (INR)", "SGST (INR)", "IGST (INR)", "Cess (INR)", "Total GST (INR)", "Gross Total (INR)"];
  wsSum.getRow(4).values = sumHeaders;
  styleHeaderRow(wsSum.getRow(4), "FF1E3A8A");

  let sRowNum = 5;
  for (const m of monthlyTrend) {
    const row = wsSum.getRow(sRowNum);
    row.values = [m.monthLabel, m.taxableValue, m.cgst, m.sgst, m.igst, m.cess, m.totalGst, m.grossAmount];
    for (let c = 2; c <= 8; c++) row.getCell(c).numFmt = "₹#,##0.00";
    sRowNum++;
  }

  // ==========================================
  // SHEET 3: ITC SUMMARY
  // ==========================================
  const wsItc = workbook.addWorksheet("ITC Summary");
  wsItc.mergeCells("A1:E1");
  wsItc.getCell("A1").value = `${ORG_NAME} - INPUT TAX CREDIT (ITC) CLASSIFICATION`;
  wsItc.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsItc.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  const itcHeaders = ["ITC Eligibility", "Status Code", "Items Count", "ITC Tax Amount (INR)", "% Share of Total GST"];
  wsItc.getRow(4).values = itcHeaders;
  styleHeaderRow(wsItc.getRow(4), "FF1E3A8A");

  let itcRowNum = 5;
  for (const itc of itcBreakdown) {
    const row = wsItc.getRow(itcRowNum);
    row.values = [itc.label, itc.eligibility, itc.itemCount, itc.itcAmount, `${itc.percentage}%`];
    row.getCell(4).numFmt = "₹#,##0.00";
    itcRowNum++;
  }
  wsItc.columns = [{ width: 24 }, { width: 20 }, { width: 16 }, { width: 22 }, { width: 22 }];

  // ==========================================
  // SHEET 4: RCM SUMMARY
  // ==========================================
  const wsRcm = workbook.addWorksheet("RCM Summary");
  wsRcm.mergeCells("A1:G1");
  wsRcm.getCell("A1").value = `${ORG_NAME} - REVERSE CHARGE MECHANISM (RCM) TRANSACTIONS`;
  wsRcm.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsRcm.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  const rcmHeaders = ["Report #", "Expense Date", "Vendor / Merchant", "Place of Supply", "Taxable Value (INR)", "GST Tax (INR)", "Gross Spend (INR)"];
  wsRcm.getRow(4).values = rcmHeaders;
  styleHeaderRow(wsRcm.getRow(4), "FF1E3A8A");

  let rcmRowNum = 5;
  for (const r of rcmTransactions) {
    const row = wsRcm.getRow(rcmRowNum);
    row.values = [r.reportNumber, r.expenseDate, r.vendorName, r.placeOfSupply || "-", r.taxableValue, r.totalGstAmount, r.grossAmount];
    row.getCell(5).numFmt = "₹#,##0.00";
    row.getCell(6).numFmt = "₹#,##0.00";
    row.getCell(7).numFmt = "₹#,##0.00";
    rcmRowNum++;
  }
  wsRcm.columns = [{ width: 18 }, { width: 16 }, { width: 28 }, { width: 18 }, { width: 20 }, { width: 18 }, { width: 20 }];

  // ==========================================
  // SHEET 5: CATEGORY SUMMARY
  // ==========================================
  const wsCat = workbook.addWorksheet("Category Summary");
  wsCat.mergeCells("A1:H1");
  wsCat.getCell("A1").value = `${ORG_NAME} - GST TAX BY EXPENSE CATEGORY`;
  wsCat.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsCat.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  const catHeaders = ["Category Name", "Item Count", "Taxable Value (INR)", "CGST (INR)", "SGST (INR)", "IGST (INR)", "Total GST (INR)", "Gross Total (INR)"];
  wsCat.getRow(4).values = catHeaders;
  styleHeaderRow(wsCat.getRow(4), "FF1E3A8A");

  let cRowNum = 5;
  for (const c of categoriesSummary) {
    const row = wsCat.getRow(cRowNum);
    row.values = [c.categoryName, c.itemCount, c.taxableValue, c.cgst, c.sgst, c.igst, c.totalGst, c.grossAmount];
    for (let col = 3; col <= 8; col++) row.getCell(col).numFmt = "₹#,##0.00";
    cRowNum++;
  }
  wsCat.columns = [{ width: 28 }, { width: 14 }, { width: 20 }, { width: 16 }, { width: 16 }, { width: 16 }, { width: 18 }, { width: 20 }];

  // ==========================================
  // SHEET 6: VENDOR SUMMARY
  // ==========================================
  const wsVen = workbook.addWorksheet("Vendor Summary");
  wsVen.mergeCells("A1:F1");
  wsVen.getCell("A1").value = `${ORG_NAME} - GST BY VENDOR / MERCHANT`;
  wsVen.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsVen.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  const venHeaders = ["Vendor Name", "Vendor GSTIN", "Item Count", "Taxable Value (INR)", "Total GST (INR)", "Gross Spend (INR)"];
  wsVen.getRow(4).values = venHeaders;
  styleHeaderRow(wsVen.getRow(4), "FF1E3A8A");

  let vRowNum = 5;
  for (const v of vendorsSummary) {
    const row = wsVen.getRow(vRowNum);
    row.values = [v.vendorName, v.vendorGstin, v.itemCount, v.taxableValue, v.totalGst, v.grossAmount];
    row.getCell(4).numFmt = "₹#,##0.00";
    row.getCell(5).numFmt = "₹#,##0.00";
    row.getCell(6).numFmt = "₹#,##0.00";
    vRowNum++;
  }
  wsVen.columns = [{ width: 30 }, { width: 20 }, { width: 14 }, { width: 20 }, { width: 18 }, { width: 20 }];

  // ==========================================
  // SHEET 7: DATA QUALITY EXCEPTIONS
  // ==========================================
  const wsExc = workbook.addWorksheet("Data Quality Exceptions");
  wsExc.mergeCells("A1:G1");
  wsExc.getCell("A1").value = `${ORG_NAME} - DATA QUALITY & COMPLIANCE EXCEPTIONS`;
  wsExc.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsExc.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF991B1B" } }; // Deep Red

  const excHeaders = ["Report #", "Expense Date", "Vendor", "Severity", "Exception Code", "Exception Title", "Issue Description"];
  wsExc.getRow(4).values = excHeaders;
  styleHeaderRow(wsExc.getRow(4), "FF991B1B");

  let eRowNum = 5;
  for (const item of exceptionsList) {
    for (const exc of item.exceptions) {
      const row = wsExc.getRow(eRowNum);
      row.values = [
        item.row.reportNumber,
        item.row.expenseDate,
        item.row.vendorName,
        exc.severity,
        exc.code,
        exc.title,
        exc.message,
      ];
      eRowNum++;
    }
  }
  wsExc.columns = [{ width: 18 }, { width: 16 }, { width: 26 }, { width: 14 }, { width: 24 }, { width: 28 }, { width: 44 }];

  // ==========================================
  // SHEET 8: APPLIED FILTERS & METADATA
  // ==========================================
  const wsMeta = workbook.addWorksheet("Applied Filters");
  wsMeta.mergeCells("A1:D1");
  wsMeta.getCell("A1").value = `${ORG_NAME} - GST REGISTER PARAMETERS`;
  wsMeta.getCell("A1").font = { name: "Calibri", size: 13, bold: true, color: { argb: "FFFFFFFF" } };
  wsMeta.getCell("A1").fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F2B5C" } };

  wsMeta.getCell("A3").value = "Company Name";
  wsMeta.getCell("B3").value = ORG_NAME;
  wsMeta.getCell("A4").value = "Address";
  wsMeta.getCell("B4").value = ORG_ADDRESS;
  wsMeta.getCell("A5").value = "Disclaimer";
  wsMeta.getCell("B5").value = GST_DISCLAIMER;
  wsMeta.getCell("A6").value = "Generated By";
  wsMeta.getCell("B6").value = `${generatedByUser.name} (${generatedByUser.email} - ${generatedByUser.role})`;
  wsMeta.getCell("A7").value = "Generated At";
  wsMeta.getCell("B7").value = timestamp;

  wsMeta.columns = [{ width: 24 }, { width: 60 }];

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
