import { PDFDocument, StandardFonts, rgb, PDFPage } from "pdf-lib";
import {
  GstAnalyticsData,
  GstRegisterRow,
  GstRegisterFilterParams,
  ORG_NAME,
  ORG_ADDRESS,
  GST_DISCLAIMER,
  TIMEZONE,
} from "./gst-register-query";
import { formatInTimeZone } from "date-fns-tz";

function formatInr(val: number | null | undefined): string {
  if (val === null || val === undefined) return "0.00";
  return Number(val).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

/**
 * Generates a formal multi-page Landscape PDF for the GST Expense Register
 */
export async function generateGstRegisterPdf(params: {
  rows: GstRegisterRow[];
  analytics: GstAnalyticsData;
  filterParams: GstRegisterFilterParams;
  generatedByUser: { name: string; email: string; role: string };
}): Promise<Uint8Array> {
  const { rows, analytics, filterParams, generatedByUser } = params;
  const { kpis, monthlyTrend, taxComponents, itcBreakdown, categoriesSummary, rcmTransactions, exceptionsList } = analytics;

  const pdfDoc = await PDFDocument.create();

  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const PAGE_WIDTH = 841.89; // Landscape A4
  const PAGE_HEIGHT = 595.28;
  const MARGIN_LEFT = 30;
  const MARGIN_RIGHT = 30;
  const MARGIN_TOP = 30;
  const MARGIN_BOTTOM = 30;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

  let currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursorY = PAGE_HEIGHT - MARGIN_TOP;

  const timestamp = formatInTimeZone(new Date(), TIMEZONE, "dd-MMM-yyyy HH:mm zzz");

  const checkNewPage = (neededHeight: number) => {
    if (cursorY - neededHeight < MARGIN_BOTTOM + 20) {
      drawFooter(currentPage);
      currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      cursorY = PAGE_HEIGHT - MARGIN_TOP;
      drawRunningHeader(currentPage);
    }
  };

  const drawRunningHeader = (page: PDFPage) => {
    page.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 18,
      width: CONTENT_WIDTH,
      height: 18,
      color: rgb(0.08, 0.2, 0.4),
    });

    page.drawText(`${ORG_NAME} - GST EXPENSE REGISTER (INTERNAL AUDIT)`, {
      x: MARGIN_LEFT + 8,
      y: cursorY - 13,
      size: 8.5,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Generated: ${timestamp} | Address: ${ORG_ADDRESS}`, {
      x: PAGE_WIDTH - MARGIN_RIGHT - 260,
      y: cursorY - 13,
      size: 7.5,
      font: fontRegular,
      color: rgb(0.85, 0.9, 0.98),
    });

    cursorY -= 28;
  };

  const drawFooter = (page: PDFPage) => {
    page.drawLine({
      start: { x: MARGIN_LEFT, y: MARGIN_BOTTOM },
      end: { x: PAGE_WIDTH - MARGIN_RIGHT, y: MARGIN_BOTTOM },
      thickness: 0.5,
      color: rgb(0.7, 0.75, 0.8),
    });

    page.drawText(GST_DISCLAIMER, {
      x: MARGIN_LEFT,
      y: MARGIN_BOTTOM - 12,
      size: 7,
      font: fontBold,
      color: rgb(0.5, 0.2, 0.2),
    });
  };

  // ==========================================
  // PAGE 1: PRIMARY HEADER & DISCLAIMER
  // ==========================================
  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 42,
    width: CONTENT_WIDTH,
    height: 42,
    color: rgb(0.08, 0.2, 0.4),
  });

  currentPage.drawText(ORG_NAME, {
    x: MARGIN_LEFT + 10,
    y: cursorY - 16,
    size: 13,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  currentPage.drawText(`Corporate Office: ${ORG_ADDRESS}`, {
    x: MARGIN_LEFT + 10,
    y: cursorY - 30,
    size: 7.5,
    font: fontRegular,
    color: rgb(0.85, 0.9, 0.98),
  });

  currentPage.drawText("INTERNAL GST EXPENSE REGISTER", {
    x: PAGE_WIDTH - MARGIN_RIGHT - 240,
    y: cursorY - 16,
    size: 11,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  currentPage.drawText(`Generated by: ${generatedByUser.name} (${generatedByUser.role})`, {
    x: PAGE_WIDTH - MARGIN_RIGHT - 240,
    y: cursorY - 30,
    size: 7.5,
    font: fontRegular,
    color: rgb(0.85, 0.9, 0.98),
  });

  cursorY -= 50;

  // Disclaimer Callout Banner
  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 20,
    width: CONTENT_WIDTH,
    height: 20,
    borderColor: rgb(0.9, 0.6, 0.2),
    borderWidth: 1,
    color: rgb(1, 0.98, 0.94),
  });

  currentPage.drawText(`NOTICE: ${GST_DISCLAIMER}`, {
    x: MARGIN_LEFT + 8,
    y: cursorY - 14,
    size: 7.5,
    font: fontBold,
    color: rgb(0.7, 0.3, 0.05),
  });

  cursorY -= 28;

  // 12 GST Summary Cards (3 rows of 4 cards)
  const cardW = (CONTENT_WIDTH - 30) / 4;
  const cardH = 34;

  const kpiRow1 = [
    { label: "GROSS EXPENSE", val: `INR ${formatInr(kpis.grossExpense)}`, color: rgb(0.08, 0.2, 0.4) },
    { label: "TAXABLE VALUE", val: `INR ${formatInr(kpis.taxableValue)}`, color: rgb(0.1, 0.3, 0.6) },
    { label: "TOTAL GST TAX", val: `INR ${formatInr(kpis.totalGst)}`, color: rgb(0.08, 0.45, 0.2) },
    { label: "ELIGIBLE ITC", val: `INR ${formatInr(kpis.eligibleItc)}`, color: rgb(0.05, 0.5, 0.25) },
  ];

  const kpiRow2 = [
    { label: "CGST TAX", val: `INR ${formatInr(kpis.cgst)}`, color: rgb(0.1, 0.35, 0.7) },
    { label: "SGST / UTGST", val: `INR ${formatInr(kpis.sgst)}`, color: rgb(0.08, 0.45, 0.3) },
    { label: "IGST TAX", val: `INR ${formatInr(kpis.igst)}`, color: rgb(0.45, 0.15, 0.6) },
    { label: "CESS TAX", val: `INR ${formatInr(kpis.cess)}`, color: rgb(0.6, 0.4, 0.1) },
  ];

  const kpiRow3 = [
    { label: "INELIGIBLE ITC", val: `INR ${formatInr(kpis.ineligibleItc)}`, color: rgb(0.6, 0.2, 0.2) },
    { label: "PENDING ITC REVIEW", val: `INR ${formatInr(kpis.pendingItcReview)}`, color: rgb(0.7, 0.45, 0.05) },
    { label: "REVERSE CHARGE (RCM)", val: `INR ${formatInr(kpis.rcmAmount)}`, color: rgb(0.3, 0.2, 0.5) },
    { label: "DATA EXCEPTIONS", val: `${kpis.exceptionCount} Flagged`, color: kpis.exceptionCount > 0 ? rgb(0.8, 0.1, 0.1) : rgb(0.1, 0.5, 0.2) },
  ];

  const renderCardRow = (cards: typeof kpiRow1) => {
    cards.forEach((card, idx) => {
      const posX = MARGIN_LEFT + idx * (cardW + 10);
      currentPage.drawRectangle({
        x: posX,
        y: cursorY - cardH,
        width: cardW,
        height: cardH,
        borderColor: rgb(0.82, 0.86, 0.92),
        borderWidth: 1,
        color: rgb(0.98, 0.99, 1),
      });

      currentPage.drawText(card.label, {
        x: posX + 8,
        y: cursorY - 12,
        size: 6.5,
        font: fontBold,
        color: rgb(0.4, 0.45, 0.5),
      });

      currentPage.drawText(card.val, {
        x: posX + 8,
        y: cursorY - 26,
        size: 9,
        font: fontBold,
        color: card.color,
      });
    });
    cursorY -= cardH + 6;
  };

  renderCardRow(kpiRow1);
  renderCardRow(kpiRow2);
  renderCardRow(kpiRow3);

  cursorY -= 10;

  // ==========================================
  // SECTION: GST BY CATEGORY SUMMARY
  // ==========================================
  currentPage.drawText("GST SUMMARY BY CATEGORY", {
    x: MARGIN_LEFT,
    y: cursorY,
    size: 9.5,
    font: fontBold,
    color: rgb(0.08, 0.2, 0.4),
  });
  cursorY -= 13;

  const catColWidths = [180, 60, 95, 80, 80, 80, 95, 110];
  const catHeaders = ["Category Name", "Items", "Taxable (INR)", "CGST (INR)", "SGST (INR)", "IGST (INR)", "Total GST (INR)", "Gross (INR)"];

  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: cursorY - 15,
    width: CONTENT_WIDTH,
    height: 15,
    color: rgb(0.08, 0.2, 0.4),
  });

  let curX = MARGIN_LEFT;
  catHeaders.forEach((h, idx) => {
    currentPage.drawText(h, {
      x: curX + 4,
      y: cursorY - 10.5,
      size: 7,
      font: fontBold,
      color: rgb(1, 1, 1),
    });
    curX += catColWidths[idx];
  });
  cursorY -= 16;

  categoriesSummary.slice(0, 8).forEach((cat, idx) => {
    checkNewPage(14);
    const isEven = idx % 2 === 0;

    currentPage.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 14,
      width: CONTENT_WIDTH,
      height: 14,
      borderColor: rgb(0.88, 0.9, 0.94),
      borderWidth: 0.5,
      color: isEven ? rgb(0.98, 0.99, 1) : rgb(1, 1, 1),
    });

    const rowVals = [
      cat.categoryName.substring(0, 26),
      String(cat.itemCount),
      formatInr(cat.taxableValue),
      formatInr(cat.cgst),
      formatInr(cat.sgst),
      formatInr(cat.igst),
      formatInr(cat.totalGst),
      formatInr(cat.grossAmount),
    ];

    let rowX = MARGIN_LEFT;
    rowVals.forEach((val, cIdx) => {
      currentPage.drawText(val, {
        x: rowX + 4,
        y: cursorY - 9.5,
        size: 6.5,
        font: cIdx === 6 || cIdx === 7 ? fontBold : fontRegular,
        color: rgb(0.1, 0.15, 0.2),
      });
      rowX += catColWidths[cIdx];
    });

    cursorY -= 14;
  });

  cursorY -= 14;

  // ==========================================
  // SECTION: ITEMIZED TRANSACTION APPENDIX
  // ==========================================
  checkNewPage(60);
  currentPage.drawText("ITEMIZED GST TRANSACTIONS APPENDIX", {
    x: MARGIN_LEFT,
    y: cursorY,
    size: 9.5,
    font: fontBold,
    color: rgb(0.08, 0.2, 0.4),
  });
  cursorY -= 13;

  const txColWidths = [75, 55, 60, 110, 80, 55, 65, 55, 55, 55, 60, 55];
  const txHeaders = ["Report #", "Date", "Invoice #", "Vendor Name", "GSTIN", "POS", "Taxable (INR)", "CGST", "SGST", "IGST", "Total GST", "ITC"];

  const renderTxHeader = () => {
    currentPage.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 15,
      width: CONTENT_WIDTH,
      height: 15,
      color: rgb(0.08, 0.2, 0.4),
    });

    let hX = MARGIN_LEFT;
    txHeaders.forEach((h, idx) => {
      currentPage.drawText(h, {
        x: hX + 3,
        y: cursorY - 10.5,
        size: 6.5,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
      hX += txColWidths[idx];
    });
    cursorY -= 16;
  };

  renderTxHeader();

  rows.forEach((r, idx) => {
    if (cursorY - 14 < MARGIN_BOTTOM + 20) {
      drawFooter(currentPage);
      currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      cursorY = PAGE_HEIGHT - MARGIN_TOP;
      drawRunningHeader(currentPage);
      renderTxHeader();
    }

    const isEven = idx % 2 === 0;
    currentPage.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 13,
      width: CONTENT_WIDTH,
      height: 13,
      borderColor: rgb(0.88, 0.9, 0.94),
      borderWidth: 0.5,
      color: isEven ? rgb(0.98, 0.99, 1) : rgb(1, 1, 1),
    });

    const txVals = [
      r.reportNumber.substring(0, 14),
      r.expenseDate,
      (r.invoiceNumber || "-").substring(0, 10),
      r.vendorName.substring(0, 18),
      (r.vendorGstin || "-").substring(0, 15),
      r.placeOfSupply || "-",
      formatInr(r.taxableValue),
      formatInr(r.cgstAmount),
      formatInr(r.sgstAmount),
      formatInr(r.igstAmount),
      formatInr(r.totalGstAmount),
      r.itcEligibility === "ELIGIBLE" ? "ELIGIBLE" : r.itcEligibility === "INELIGIBLE" ? "INELIG" : "REVIEW",
    ];

    let tX = MARGIN_LEFT;
    txVals.forEach((val, cIdx) => {
      currentPage.drawText(val, {
        x: tX + 3,
        y: cursorY - 9,
        size: 6,
        font: cIdx === 10 ? fontBold : fontRegular,
        color: rgb(0.1, 0.15, 0.2),
      });
      tX += txColWidths[cIdx];
    });

    cursorY -= 13;
  });

  drawFooter(currentPage);

  // Add Page Numbers
  const totalPages = pdfDoc.getPageCount();
  const pages = pdfDoc.getPages();
  for (let i = 0; i < totalPages; i++) {
    const page = pages[i];
    const pageNumStr = `Page ${i + 1} of ${totalPages}`;
    page.drawText(pageNumStr, {
      x: PAGE_WIDTH - MARGIN_RIGHT - fontRegular.widthOfTextAtSize(pageNumStr, 7),
      y: MARGIN_BOTTOM - 12,
      size: 7,
      font: fontRegular,
      color: rgb(0.5, 0.55, 0.6),
    });
  }

  return await pdfDoc.save();
}
