import { PDFDocument, StandardFonts, rgb, degrees, PDFPage } from "pdf-lib";
import { DetailedExpenseReportRow, DetailedReportSummaryTotals, DetailedReportFilterParams, TIMEZONE } from "./report-query";
import { ALL_REPORT_COLUMNS, DEFAULT_COLUMN_IDS } from "./excel-export";
import { formatInTimeZone } from "date-fns-tz";

const ORG_NAME = "RADICAL HEALTH TECH PVT LTD";
const ORG_SUBTITLE = "Action Area II , Ecospace | GSTIN: 19AAACR1234A1Z5";

function formatInr(val: number | null | undefined): string {
  if (val === null || val === undefined) return "0.00";
  return Number(val).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

/**
 * Generates a formal, multi-page landscape PDF for the Detailed Expense Report
 */
export async function generateDetailedExpenseReportPdf(params: {
  rows: DetailedExpenseReportRow[];
  summaryTotals: DetailedReportSummaryTotals;
  filterParams: DetailedReportFilterParams;
  visibleColumnIds?: string[];
  generatedByUser: { name: string; email: string; role: string };
  isSummaryOnly?: boolean;
}): Promise<Uint8Array> {
  const { rows, summaryTotals, filterParams, visibleColumnIds, generatedByUser, isSummaryOnly } = params;

  const pdfDoc = await PDFDocument.create();

  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontOblique = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

  // Landscape A4 Dimensions: 841.89 x 595.28 points
  const PAGE_WIDTH = 841.89;
  const PAGE_HEIGHT = 595.28;
  const MARGIN_LEFT = 30;
  const MARGIN_RIGHT = 30;
  const MARGIN_TOP = 32;
  const MARGIN_BOTTOM = 32;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

  let currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursorY = PAGE_HEIGHT - MARGIN_TOP;

  // Selected Columns - if too wide, restrict to landscape printable subset (max 9-10 columns per row)
  const defaultLandscapeCols = [
    "reportNumber",
    "tagTitle",
    "tagStatus",
    "expenseDate",
    "vendorName",
    "categoryName",
    "itemDescription",
    "taxableValue",
    "totalGstAmount",
    "itemAmount",
    "submittedBy",
  ];

  const candidateCols = visibleColumnIds && visibleColumnIds.length > 0 ? visibleColumnIds : defaultLandscapeCols;
  const activeColIds = candidateCols.slice(0, 11); // Ensure maximum 11 columns fit legibly

  const columns = activeColIds
    .map((id) => ALL_REPORT_COLUMNS[id])
    .filter(Boolean);

  // Calculate dynamic column widths to fill CONTENT_WIDTH
  const baseTotalWidth = columns.reduce((acc, c) => acc + (c.width || 18), 0);
  const colWidths = columns.map((c) => Math.floor(((c.width || 18) / baseTotalWidth) * CONTENT_WIDTH));

  const checkNewPage = (neededHeight: number) => {
    if (cursorY - neededHeight < MARGIN_BOTTOM + 20) {
      drawFooter(currentPage);
      currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      cursorY = PAGE_HEIGHT - MARGIN_TOP;
      drawHeader(currentPage, true);
    }
  };

  const drawHeader = (page: PDFPage, isSubsequent: boolean = false) => {
    const timestamp = formatInTimeZone(new Date(), TIMEZONE, "dd-MMM-yyyy HH:mm zzz");

    if (isSubsequent) {
      // Compact Running Header
      page.drawRectangle({
        x: MARGIN_LEFT,
        y: cursorY - 18,
        width: CONTENT_WIDTH,
        height: 18,
        color: rgb(0.08, 0.2, 0.4),
      });

      page.drawText(`${ORG_NAME} - DETAILED EXPENSE REPORT`, {
        x: MARGIN_LEFT + 6,
        y: cursorY - 13,
        size: 8,
        font: fontBold,
        color: rgb(1, 1, 1),
      });

      page.drawText(`Generated: ${timestamp} | Records: ${rows.length}`, {
        x: PAGE_WIDTH - MARGIN_RIGHT - 170,
        y: cursorY - 13,
        size: 7.5,
        font: fontRegular,
        color: rgb(0.85, 0.9, 0.98),
      });

      cursorY -= 26;
      drawTableHeader(page);
      return;
    }

    // Full Primary Header on Page 1
    page.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 38,
      width: CONTENT_WIDTH,
      height: 38,
      color: rgb(0.08, 0.2, 0.4),
    });

    page.drawText(ORG_NAME, {
      x: MARGIN_LEFT + 10,
      y: cursorY - 16,
      size: 12,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText(ORG_SUBTITLE, {
      x: MARGIN_LEFT + 10,
      y: cursorY - 30,
      size: 7.5,
      font: fontRegular,
      color: rgb(0.85, 0.9, 0.98),
    });

    page.drawText("DETAILED EXPENSE & GST REPORT", {
      x: PAGE_WIDTH - MARGIN_RIGHT - 210,
      y: cursorY - 16,
      size: 11,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText(`Generated by: ${generatedByUser.name} (${generatedByUser.role})`, {
      x: PAGE_WIDTH - MARGIN_RIGHT - 210,
      y: cursorY - 30,
      size: 7.5,
      font: fontRegular,
      color: rgb(0.85, 0.9, 0.98),
    });

    cursorY -= 46;

    // Filter Summary Box
    const filterDescParts: string[] = [];
    if (filterParams.filterMode === "DATE_RANGE") {
      filterDescParts.push(`Date Range (${filterParams.dateBasis || "EXPENSE_DATE"}): ${filterParams.fromDate || "All"} to ${filterParams.toDate || "All"}`);
    } else if (filterParams.filterMode === "MULTIPLE_MONTHS") {
      filterDescParts.push(`Months: ${filterParams.selectedMonths?.join(", ") || "All"} (Year ${filterParams.year || new Date().getFullYear()})`);
    }
    if (filterParams.status) filterDescParts.push(`Status: ${filterParams.status}`);
    if (filterParams.vendorName) filterDescParts.push(`Vendor: ${filterParams.vendorName}`);
    if (filterParams.globalSearch) filterDescParts.push(`Search: "${filterParams.globalSearch}"`);

    page.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 20,
      width: CONTENT_WIDTH,
      height: 20,
      borderColor: rgb(0.8, 0.85, 0.9),
      borderWidth: 0.5,
      color: rgb(0.96, 0.97, 1),
    });

    page.drawText(
      `Applied Filters: ${filterDescParts.length > 0 ? filterDescParts.join(" | ") : "All Records (No Filters)"}`,
      {
        x: MARGIN_LEFT + 8,
        y: cursorY - 14,
        size: 7.5,
        font: fontRegular,
        color: rgb(0.2, 0.25, 0.35),
      }
    );

    cursorY -= 28;

    // Financial KPI Cards Row
    drawFinancialSummaryCards(page);
    cursorY -= 48;

    if (!isSummaryOnly) {
      drawTableHeader(page);
    }
  };

  const drawFinancialSummaryCards = (page: PDFPage) => {
    const cardWidth = (CONTENT_WIDTH - 30) / 4;
    const cardHeight = 38;

    const cards = [
      { label: "TOTAL ITEMS", val: `${summaryTotals.itemCount} Items`, color: rgb(0.08, 0.2, 0.4) },
      { label: "TAXABLE VALUE", val: `INR ${formatInr(summaryTotals.totalTaxableValue)}`, color: rgb(0.15, 0.2, 0.3) },
      { label: "TOTAL GST TAX", val: `INR ${formatInr(summaryTotals.totalGst)}`, color: rgb(0.1, 0.35, 0.7) },
      { label: "GRAND TOTAL", val: `INR ${formatInr(summaryTotals.grandTotal)}`, color: rgb(0.08, 0.45, 0.2) },
    ];

    cards.forEach((card, idx) => {
      const posX = MARGIN_LEFT + idx * (cardWidth + 10);
      page.drawRectangle({
        x: posX,
        y: cursorY - cardHeight,
        width: cardWidth,
        height: cardHeight,
        borderColor: rgb(0.8, 0.85, 0.9),
        borderWidth: 1,
        color: rgb(0.98, 0.99, 1),
      });

      page.drawText(card.label, {
        x: posX + 8,
        y: cursorY - 14,
        size: 7,
        font: fontBold,
        color: rgb(0.4, 0.45, 0.5),
      });

      page.drawText(card.val, {
        x: posX + 8,
        y: cursorY - 30,
        size: 10,
        font: fontBold,
        color: card.color,
      });
    });
  };

  const drawTableHeader = (page: PDFPage) => {
    page.drawRectangle({
      x: MARGIN_LEFT,
      y: cursorY - 18,
      width: CONTENT_WIDTH,
      height: 18,
      color: rgb(0.08, 0.2, 0.4),
    });

    let currentX = MARGIN_LEFT;
    columns.forEach((col, idx) => {
      const colW = colWidths[idx];
      const headerText = col.header;
      page.drawText(headerText.substring(0, 18), {
        x: currentX + 4,
        y: cursorY - 12,
        size: 7.5,
        font: fontBold,
        color: rgb(1, 1, 1),
      });
      currentX += colW;
    });

    cursorY -= 20;
  };

  const drawFooter = (page: PDFPage) => {
    page.drawLine({
      start: { x: MARGIN_LEFT, y: MARGIN_BOTTOM },
      end: { x: PAGE_WIDTH - MARGIN_RIGHT, y: MARGIN_BOTTOM },
      thickness: 0.5,
      color: rgb(0.7, 0.75, 0.8),
    });

    page.drawText("CONFIDENTIAL - INTERNAL ANALYTICAL REPORT", {
      x: MARGIN_LEFT,
      y: MARGIN_BOTTOM - 12,
      size: 7,
      font: fontBold,
      color: rgb(0.5, 0.55, 0.6),
    });
  };

  drawHeader(currentPage, false);

  if (!isSummaryOnly) {
    // Render Data Rows
    for (let rIdx = 0; rIdx < rows.length; rIdx++) {
      const row = rows[rIdx];
      const rowHeight = 18;
      checkNewPage(rowHeight + 4);

      const isEven = rIdx % 2 === 0;
      currentPage.drawRectangle({
        x: MARGIN_LEFT,
        y: cursorY - rowHeight,
        width: CONTENT_WIDTH,
        height: rowHeight,
        borderColor: rgb(0.88, 0.9, 0.94),
        borderWidth: 0.5,
        color: isEven ? rgb(0.98, 0.99, 1) : rgb(1, 1, 1),
      });

      let currentX = MARGIN_LEFT;
      columns.forEach((col, colIdx) => {
        const colW = colWidths[colIdx];
        const rawVal = col.accessor(row);
        let strVal = rawVal !== null && rawVal !== undefined ? String(rawVal) : "-";
        if (typeof rawVal === "number" && col.numFmt) {
          strVal = formatInr(rawVal);
        }

        // Clip text length to fit column width
        const maxLen = Math.floor(colW / 4.8);
        if (strVal.length > maxLen) {
          strVal = `${strVal.substring(0, maxLen - 2)}..`;
        }

        const isNumeric = col.align === "right";
        const textX = isNumeric
          ? currentX + colW - fontRegular.widthOfTextAtSize(strVal, 7) - 4
          : currentX + 4;

        currentPage.drawText(strVal, {
          x: Math.max(currentX + 2, textX),
          y: cursorY - 12,
          size: 7,
          font: col.id === "itemAmount" || col.id === "reportNumber" ? fontBold : fontRegular,
          color: rgb(0.1, 0.15, 0.2),
        });

        currentX += colW;
      });

      cursorY -= rowHeight;
    }
  }

  drawFooter(currentPage);

  // Add Page Numbers
  const totalPages = pdfDoc.getPageCount();
  const pages = pdfDoc.getPages();
  for (let i = 0; i < totalPages; i++) {
    const page = pages[i];
    const pageNumStr = `Page ${i + 1} of ${totalPages}`;
    page.drawText(pageNumStr, {
      x: PAGE_WIDTH - MARGIN_RIGHT - fontRegular.widthOfTextAtSize(pageNumStr, 7),
      y: MARGIN_BOTTOM - 12,
      size: 7,
      font: fontRegular,
      color: rgb(0.5, 0.55, 0.6),
    });
  }

  return await pdfDoc.save();
}
